### PR TITLE
Js interface

### PR DESCRIPTION
**Pull request by schmidsi**
This is a js-only implementation for the ProofOfEmail contract to be used on the server side.

I made one [enhancement to the contract](https://github.com/melonproject/email-faucet/blob/07ca50bba961383f093ba8cf0aaa85bfbb8cdf14/imports/truffle/contracts/ProofOfEmail.sol#L36-L46): Anybody can now verify an email as long as she knows the code. --> We can now verify emails and pay the gas completely on the server side, since new users will have 0 K-ETH.

The contract is still backwards compatibly, so users with K-ETH can verify their mails manually (and pay for the gas)

### CODE REVIEW

**Comment by retotrinkler** [comment]
looks v good to me!
@travs what do u think?

**Comment by retotrinkler** [comment]
merging to not delay

**Comment by travs** [comment]
Yeah, looks like some of it improves on the satellite code so it should work fine.

Need to add `truffle.js`, `truffle:deploy` npm script, and actually send emails from the server now.
That last one you can get from satellite too. Not sure if we want to use sendgrid like I did there (prototype basically), or meteor native emails which there is an API for (not sure how the service would actually work).

**Comment by schmidsi** [comment]
We kind of changed the strategy and leave this repo orphaned for now: K-ETH is automatically sent to new users as seen in [daemon#20](https://github.com/melonproject/daemon/pull/20).

For mailings: It is highly recommended to use a mailing service like Mailgun. The meteor integrated mailing functionality is considered as SPAM from most of the big mail providers.

**Pull request merged**
